### ISSUE TITLE
detailed usage of readDepth

### ISSUE THREAD

**Issue by marsa2** [chrisamiller/readDepth#1]
Hi Chris,

where can I find a full reference manual for readDepth ? It looks like the usage section in a Readme file is not complete. Would be helpful to have a detailed readDepth documentation. 

Thank you

**Comment by chrisamiller** [comment]
Thanks for noticing that error in the usage section - it got truncated when migrating the project here from google code. It's been restored.

You're right that a detailed manual would be nice, but I don't have anything of the sort created, and am not currently planning additional development on to this project, other than the occasional bugfix. The readme is fairly comprehensive, and the help files within R contain more detailed information on the commands. Best of luck!
