### ISSUE TITLE
build annotations

### ISSUE THREAD

**Issue by ChuanJ** [chrisamiller/readDepth#10]
Hi,
I want to build the annotation files by myself cause I am using hg38. Would you please tell me how to build them?
Best,

**Comment by chrisamiller** [comment]
Unfortunately, the scripts for generating those annotations have been lost in one of the data migrations.  The principles are straightforward, though, and the scripts used to generate annotations for copyCat (a more recent tool) should get you most of the way there:  https://wustl.app.box.com/folder/141271265987?s=3950x2fdi5ra1tjxzk73l9hq5l0y7kzl

Best of luck!

**Comment by ChuanJ** [comment]
Thanks a lot! One quick question: is that possible to detect CNV from bisulfite sequencing data using these two tools?

**Comment by chrisamiller** [comment]
Yes - whole Genome bisulfite works just fine for CN detection

**Comment by ChuanJ** [comment]
And how about RRBS? Sorry, too many questions...

**Comment by chrisamiller** [comment]
No, the premise of these packages is that you're getting unbiased coverage across the genome and that depth can be converted to ploidy

**Comment by ChuanJ** [comment]
Okay, thanks for this important information!!!
