### ISSUE TITLE
Error with libraries

### ISSUE THREAD

**Issue by Danigore25** [chrisamiller/readDepth#12]
Hello, I've tried to run readDepth but R told me that I can't because of the lack of libraries, but I had them in two of my roots. Also, I've deleted them from my repositories and I couldn't download others like DNAcopy, my laptop says that these libraries can't be updated. I really tried to update them, and I still can't run the algorithm. What can I do?

**Comment by chrisamiller** [comment]
Apologies, but troubleshooting your R installation issues are beyond the scope of what I can help with here. You might have better luck from someone local who is knowledgeable in R.

That said, readDepth is no longer supported, and while it has a few niche uses, I generally recommend using other algorithms at this point - see: https://github.com/chrisamiller/readDepth#exclamation-notice

Best of luck
