### ISSUE TITLE
Interpretation of Copy Number Alteration Analysis Results

### ISSUE THREAD

**Issue by AnkitYGeneSeq** [chrisamiller/readDepth#14]
Hi Chrisamiller,

I am currently using your readDepth tool for copy number alteration analysis, and I have obtained the segs.dat file as an output. After calculating the mean of the absolute copy number calls for each gene, I am now seeking guidance on how to interpret my results.

Could you please provide some insights or guidelines on how to interpret the calculated mean of the absolute copy number for each gene? Any information or suggestions you can offer would be greatly appreciated.

**Comment by chrisamiller** [comment]
Missed this until now. If you're still looking for guidance, there is lots of it to be found on the BioStars forum. You might start with these:

https://www.biostars.org/p/112310/
https://www.biostars.org/p/13478/

Search more if you have specific questions, or feel free to open a new question if things are still unclear.  Best of luck!
