### ISSUE TITLE
downloading annotations

### ISSUE THREAD

**Issue by MajidGene** [chrisamiller/readDepth#15]
I need to use readDepth package in my project, but I cant download annotations. not by get annotations() and not manually. would you please help me?

**Comment by chrisamiller** [comment]
The downloads page here appears to work correctly for me. What errors/problems are you having? https://wustl.app.box.com/s/yimsngan0v1rc4vsa1b3uhe4ek30rlp8

**Comment by MajidGene** [comment]
> The downloads page here appears to work correctly for me. What errors/problems are you having? https://wustl.app.box.com/s/yimsngan0v1rc4vsa1b3uhe4ek30rlp8

yes it works correct, it was because of my location, The site did not allow me to download without any error message. I fixed it. thank you
