### ISSUE TITLE
Error regarding readDepth

### ISSUE THREAD

**Issue by ankita0007** [chrisamiller/readDepth#3]
What is entrypoints? Do we have to put some input information in the entrypoints directory present inside the annotation directory? As I am getting below mentioned error while creating the readDepth object.
rdo = new("rdObject")
Error in read.table("annotations/entrypoints", sep = "\t", quote = "",  : 
  no lines available in input

**Comment by chrisamiller** [comment]
The entrypoints file is just a tab-delimited file with the chromosome name, it's length, and it's ploidy. An example file for hg19 human male is here:
https://xfer.genome.wustl.edu/gxfer1/project/cancer-genomics/readDepth/entrypoints.hg19.male
