### ISSUE TITLE
PlotSegments.R

### ISSUE THREAD

**Issue by dtm2117** [chrisamiller/readDepth#5]
Hi Chris,

I know this tool/post is very old, but I found that you had uploaded a script to plot CNV based on a seg file. While I don't use ReadDepth, I do have seg files generated from VarScan2 and I'm looking to plot the data just like you have in this post:   https://www.biostars.org/p/17762/

Any chance that the script still exists somewhere? 

Best,
David

**Comment by chrisamiller** [comment]
That's still available on the downloads page (linked to in the README)
https://xfer.genome.wustl.edu/gxfer1/project/cancer-genomics/readDepth/index.html

Best of luck!
