### ISSUE TITLE
Error in `rdo = new("rdObject")`

### ISSUE THREAD

**Issue by sssimonyang** [chrisamiller/readDepth#7]
When I prepared all data and start to run Rscript you give,
run script
```
rdo = new("rdObject")
```
have error follows
```
Error in { : task 1 failed - "cannot open the connection"
```
It seems like this line of script have a connection to somewhere.
I want to wonder how to fix it .
Thank you

**Comment by solo7773** [comment]
> When I prepared all data and start to run Rscript you give,
> run script
> 
> ```
> rdo = new("rdObject")
> ```
> 
> have error follows
> 
> ```
> Error in { : task 1 failed - "cannot open the connection"
> ```
> 
> It seems like this line of script have a connection to somewhere.
> I want to wonder how to fix it .
> Thank you

I got the same error. Seems the names of files download from the provided website do not follow the rule of rdObject

The downloaded file could be untarred like this, tar --xform 'flags=r;s/chr//' -xf cap.tar

or rename file names after untar

rename  's/chr//' *

**Comment by sssimonyang** [comment]
Thank you for give me way to fix.
