### ISSUE TITLE
Annotation files

### ISSUE THREAD

**Issue by Inmafc** [chrisamiller/readDepth#9]
As it is specified in the README file to obtain the annotation files it is necessary to have those programs: runEachChr.sh, allSeq.pl and mapAndGc.pl.
```
$ tar -zxvf createCustomAnnotations.v1.tar.gz
createCustomAnnotations.v1/
createCustomAnnotations.v1/runEachChr.sh
createCustomAnnotations.v1/allSeq.pl
createCustomAnnotations.v1/mapAndGc.pl
createCustomAnnotations.v1/README
```
However, I can't find them in the link provided. Are they still available or is there another way to obtain the annotation files needed?

**Comment by chrisamiller** [comment]
Thanks for the heads up. I've relocated the files from that defunct server and updated the links in the README
